### ISSUE TITLE
Nothing generated when adding in bulk | Arch Linux

### ISSUE THREAD

**Issue by yaoberh** [migaku-official/Migaku-Anki-Addon#38]
When trying to add definitions, images, audio or example sentences, it shows the progress bar but nothing gets added after it has finished. Options in the Manage note types are configured correctly and no errors show up either before nor after.
Any suggestions?

**Comment by RicBent** [comment]
Hey, thanks for the error report!

Can you start Anki via the command line and post the output here?

**Comment by MinmoTech** [comment]
Do you still get this issue with the latest released versions?

If yes, please re-open the issue :)
