### ISSUE TITLE
Cannot create or clone preset/option group

### ISSUE THREAD

**Issue by robertkaucher** [migaku-official/Migaku-Anki-Addon#39]
After installing Migaku I am no longer able to create or clone a preset. When I then disable Migaku and restart Anki, I am able to create a new preset.

I am on a MacBook Pro M1, but I also found this Reddit post with a person who is on a Lenovo (likely running Windows).
https://www.reddit.com/r/Anki/comments/ullp0g/i_cant_create_presets/

I have uploaded a screen recording of me duplicating the issue. https://drive.google.com/file/d/1RYrrvvTwskJWlJyQddubJN7-FZ0cvEuu/view?usp=sharing

I just signed up for Migaku (monthly) yesterday and downloaded the version of the add-on from the Migaku.io website (downloads page).

**Comment by robertkaucher** [comment]
I just tested with the version on AnkiWeb and it has the same issue.

**Comment by snagels** [comment]
Really annoying bug. Any update on this matter ?

**Comment by RicBent** [comment]
Halfway fixed on my end. Will very likely be in the next update~

**Comment by MinmoTech** [comment]
If this issue still occurs on the latest versions, please reopen this :)

(I sadly cannot watch the video posted above because it has been deleted)
