### ISSUE TITLE
Day off doesn't reschedule overdue cards

### ISSUE THREAD

**Issue by MinmoTech** [migaku-official/Migaku-Anki-Addon#66]
Report: https://discord.com/channels/752293144917180496/944336185029971978/1125438933619179580

In the old extension, when the sick day feature was used, all reviews of the current day would be rescheduled over the following few days.

This doesn't actually work currently.

A description of how sick day worked previously can be found here under "sick day": https://legacy.migaku.io/tools-guides/migaku-vacation/guide/

**Comment by hgiesel** [comment]
(related: https://github.com/migaku-official/Migaku-Anki-Addon/issues/67)

**Comment by MinmoTech** [comment]
Ahh I see

Then yes, implementing the "Catch up" feature would get higher priority.
