### ISSUE TITLE
[FEATURE] Use ffmpeg-normalize to level audio volume

### ISSUE THREAD

**Issue by MinmoTech** [migaku-official/Migaku-Anki-Addon#8]
Since the volume of audio files from sources like forvo can be very inconsistent, I'd like to be able to use [ffmpeg-normalize](https://github.com/slhck/ffmpeg-normalize) to level the volume.

**Comment by RicBent** [comment]
Note: The implementation was disabled shortly before the alpha release because it requires ffprobe which isn't currently installed automatically.

**Comment by MinmoTech** [comment]
This has been implemented a while ago :)
